### ISSUE TITLE
Connections that were never activated should be considered idle

### ISSUE THREAD

**Issue by jacobbaskin** [tylerb/graceful#101]
By default, Chrome (for instance) opens two TCP connections to servers to speed up subsequent calls. If one of those connections is never used, it will prevent the server from shutting down until the connection gets closed from the client side or timed out on the server side. This means that orderly shutdowns when running servers for development take some time rather than being instantaneous.

Is there a particular reason why newly-added connections need to be treated differently from idle connections? If they are ever used they'll become active anyway. Happy to produce a PR for this.

**Comment by tylerb** [comment]
Makes sense. Please put together a PR.

**Comment by jacobbaskin** [comment]
I did notice that you mentioned this issue in the README ("If you set the timeout to 0, it waits for all connections to the server to disconnect before shutting down") but you do disconnect idle requests...which (barring Comet-style requests) should be sufficient to shut down most servers immediately even with timeout of 0.
