### ISSUE TITLE
Help with behavior of Stop()

### ISSUE THREAD

**Issue by mg03** [tylerb/graceful#104]
Hi
Firstly, this is an awesome package, i have used it almost everywhere im setting up api's.

I am using Stop() functionality in one of the api's, like so

Timeout = time.Duration(30)*time.Second
<seup of srv and other handlers/etc here>
srv.Stop(Timeout)

So my understanding is that there will be a wait of 30 seconds prior to closing the channel which will effectively close the listener.

But as soon as Stop(30) is executed, the server is shutdown.

What am I missing? Please help...

**Comment by F21** [comment]
If there are no active connections to the server, then it shuts down immediately. The behavior is to wait for a maximum of 30 seconds. If there are still connections after the 30-second timeout, the connections are forcefully terminated.

**Comment by mg03** [comment]
@F21 : hmmm thats strange

My test case was 

So the server was serving on localhost:9091

The server has two routes /stat  and /failover

/stat just returns active and HTTP 200 ok

/failover shoots a message to a channel on the other end of the channel there is a goroutine which
runs srv.Stop(30)

Then on another window

while true; do curl -v localhost:9091/stat > /dev/null 2>&1; if [ $? -ne 0 ]; then break; fi; done


On third window

curl localhost:9091/failover

As soon as the command on third window is run , the curl on second window breaks , i would expect it to continue for 30 secs and then break , is my understanding flawed?

**Comment by F21** [comment]
When calling `while true; do curl -v localhost:9091/stat > /dev/null 2>&1; if [ $? -ne 0 ]; then break; fi; done`, is it possible that the call to `localhost:9091/failover`, happened between an active request? If that is the case, the server would shut down right away.

What was the error from CURL for  `while true; do curl -v localhost:9091/stat > /dev/null 2>&1; if [ $? -ne 0 ]; then break; fi; done` when it breaks?

**Comment by mg03** [comment]
This is the output from 
while true; do curl -v localhost:9091/stat 2>&1; if [ $? -ne 0 ]; then break; fi; done when i fire of a /failover in another window
 Trying ::1...
* connect to ::1 port 9091 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 9091 failed: Connection refused
* Failed to connect to localhost port 9091: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 9091: Connection refused

**Comment by F21** [comment]
That seems correct to me. Once the server is shut down, it should will not be able to accept any connections.

It is possible that this is happening:
1. Connection is opened to the server and completes (because the response body is very small and not much handling was required, it completes almost instantly).
2. Right after completion, the server shuts down.
3. Curl tries to open another connection and was rejected.

My suggestion would be to add a `time.Sleep(40*time.Second)` to the handler for `/stat`. Open just 1 connection to that endpoint using curl, then initiate shut down at `/failover`. You should then see that the request is forcefully terminated after timing out at 30 seconds.

**Comment by mg03** [comment]
Hi

yeah the connection was closing because the response body was too small....

so i tested with a simulated slow http using `https://github.com/marant/goloris` ... and i can say that for sure the server waited for 30 secs prior to shutting down ...

i should have tested better prior to opening ticket, sorry for inconvenience

thanx 

ps: i dont know what is the process/accepted norm to close ticket, should I or will you, let me know if I  should.

**Comment by F21** [comment]
Glad you got it working! 😄 

If you were able to resolve the issue, go ahead and close the issue 😄

**Comment by mg03** [comment]
Resolved, Closing , thank you :)
