### ISSUE TITLE
Zero downtime deployments

### ISSUE THREAD

**Issue by sumakumardey** [tylerb/graceful#105]
current graceful implementation doesn't support feature like the graceful restart where we can load new code on restart can we implement something [https://grisha.org/blog/2014/06/03/graceful-restart-in-golang/](url) it would actually be helpful in the zero downtime deployments.

**Comment by F21** [comment]
@sumakumardey I think [facebook/grace](https://github.com/facebookgo/grace) should be pretty close to what you're looking for.
