### ISSUE TITLE
Timing purpose

### ISSUE THREAD

**Issue by isaldana** [tylerb/graceful#40]
It looks like in https://github.com/tylerb/graceful/blob/master/graceful.go#L175-L177, the beginning of the connection is timed, but that timing is later removed here https://github.com/tylerb/graceful/blob/master/graceful.go#L181-L183 and never used.  Any reason why that code is there?  It would be awesome to expose the connection timing to the `ConnState` handler here https://github.com/tylerb/graceful/blob/master/graceful.go#L186

**Comment by tylerb** [comment]
That is actually debug code I added while working on some data race issues. I completely forgot to remove it.

I'd prefer not to change the signature of the connection state handler, as it conforms to the same signature as that in the http package. However, as you say, there could be some use in knowing how long a connection took.

However, this is probably a higher level concern. For example, I just a negroni middleware function to capture the duration of my requests. Would this satisfy your use case?

**Comment by isaldana** [comment]
Cool, I was just wondering.  That works for me, thanks!
