### ISSUE TITLE
Pre-privilege dropping listening

### ISSUE THREAD

**Issue by hlandau** [tylerb/graceful#55]
I have an application in which an HTTP server binds to privileged ports, then drops privileges and starts serving. In order to do this, I have to create my own net.Listener. This is rather cumbersome and doesn't take advantage of connection limiting.

Calling .ListenAndServe() before privilege dropping creates a race condition, a brief window of time where HTTP requests could be served by a non-privilege-dropped connection.

What would be nice is some sort of .PreListen() method which opens the listener but does not serve. If .ListenAndServe() is then called, it uses the existing listener if .PreListen() was called.

If I wrote this code, would you be interested in merging it?

**Comment by tylerb** [comment]
I may be misunderstanding the problem at hand, but can't you create your own listener, then pass it to https://godoc.org/github.com/tylerb/graceful#Server.Serve after you've dropped privileges?

**Comment by hlandau** [comment]
Using netutil.LimitListener? Yes. Workarounds are possible, but I was wondering if you were interested in streamlining this use case.

**Comment by tylerb** [comment]
I don't see it as a workaround. Those methods specifically exist to allow for extra/custom configuration for use cases such as these. I don't see how the approach you are proposing is easier or better than simply creating your own listener and passing it to `Serve`. Graceful doesn't have `LimitListener` support anyway, and I don't want to add it. Graceful is about gracefully shutting down.

**Comment by hlandau** [comment]
Huh?

https://github.com/tylerb/graceful/blob/master/graceful.go#L115

**Comment by tylerb** [comment]
Hah! I completely forgot that was in there. Hmm.

In that case, it would make sense to create a `Listen` function similar to `ListenTLS` that returned a listening listener you can then pass to `Serve`.

Does that sound like an appropriate solution to your problem?

I also noticed we're not using the LimitListener everywhere. That should probably be moved to the `Serve` method and wrap the listener there so there is a single place it happens. I'll add another issue for that.

**Comment by hlandau** [comment]
>I also noticed we're not using the LimitListener everywhere. That should probably be moved to the Serve method and wrap the listener there so there is a single place it happens. I'll add another issue for that.

This sounds like a good idea. This would make a .Listen() method equivalent to net.Listen, so a bit superfluous. net/http doesn't provide such a method. Since you made a new issue I'll close this.
