### ISSUE TITLE
"use of closed network connection" error returned by Serve()

### ISSUE THREAD

**Issue by databus23** [tylerb/graceful#57]
I'm just trying this out and I noticed that `ListenAndServe` and `ListenAndServeTLS` always return an error for me when shutting down gracefully.
The error I'm seeing is:

```
accept tcp 127.0.0.1:1234: use of closed network connection
```

Thats a bit unfortunate, normally an error returned by `ListenAndServe` indicates that there was a problem binding the listening socket.
Is this a known problem or is there something wrong with my setup? I'm on OSX, go 1.5.2.

Example code to reproduce:
```
import (
	"fmt"
	"net/http"
	"os"

	"gopkg.in/tylerb/graceful.v1"
)

func main() {

	srv := &graceful.Server{
		Server: &http.Server{
			Addr: ":1234",
			Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Write([]byte("hello world"))
			}),
		},
	}

	if err := srv.ListenAndServe(); err != nil {
		fmt.Println("error: ", err)
		os.Exit(1)
	}
}
```

**Comment by tylerb** [comment]
Yep I'm getting that also. Trying to track it down now.

**Comment by databus23** [comment]
Awesome! Thanks so much for attending to this in no-time. :thumbsup:

**Comment by tylerb** [comment]
Sure thing! :)
