### ISSUE TITLE
graceful not working for hijacked (websocket) connections

### ISSUE THREAD

**Issue by databus23** [tylerb/graceful#58]
I just discovered that unfortunately graceful does not work for my use case.
I want it to wait for long lived websocket connections. But those connections seem to be discounted as soon as they are `hijacked`. So they don't really count as active connections at all.
I'm not really familiar to the internal workings of the http servers connection handling but looking at the code and specifically at 33d203351af9e6b2e733a3f10d11ffb726d66f30 it seems to me there is no easy way of making graceful work for highjacked connections. Is this correct or is there a way to make graceful wait for all connections the http server?

**Comment by tylerb** [comment]
Graceful explicitly does not handle websocket connections. Graceful immediately disregards any connection that gets hijacked because the hijacked connection no longer sends notifications on the `ConnState` callback, so graceful has no way of managing it.
