### ISSUE TITLE
Doesn't serve http/2

### ISSUE THREAD

**Issue by F21** [tylerb/graceful#66]
I have a simple https webserver like so:

```go
package main

import (
	//"gopkg.in/tylerb/graceful.v1"
	"net/http"
)

func main() {

	srv := &http.Server{Addr: ":https"}
	srv.ListenAndServeTLS("cert.crt", "key.pem")
}
```

If I build it and run in and then access it via Chrome, I can see that it uses http/2 (h2) from the dev tools.

If I add graceful into the mix, it only uses http/1.1:

```go
package main

import (
	"gopkg.in/tylerb/graceful.v1"
	"net/http"
	"time"
)

func main() {

	srv := &http.Server{Addr: ":https"}
	graceful.ListenAndServeTLS(srv, "cert.crt", "key.pem", 10*time.Second)
}
```

**Comment by F21** [comment]
It looks like the native go library needs the `tlsConfig` set:

```go
cert := []byte("-----BEGIN CERTIFICATE-----...")

    key := []byte("-----BEGIN RSA PRIVATE KEY-----...")

    mux := http.NewServeMux()

    mux.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
        fmt.Fprintf(w, "Welcome to the home page!")
    })

    xcert, err := tls.X509KeyPair(cert, key)

    if err != nil {
        panic(err)
    }

    tlsConf := &tls.Config{
        Certificates: []tls.Certificate{xcert},
    }

    tlsConf.BuildNameToCertificate()

    srv := &graceful.Server{
        Timeout: 0,

        Logger: graceful.DefaultLogger(),

        Server: &http.Server{
            Addr:      ":https",
            Handler:   mux,
            TLSConfig: tlsConf,
        },
    }

    srv.ListenAndServeTLSConfig(tlsConf)
```

- It seems redundant to have to pass `tlsConf` to both the `net/http Server` struct and `ListenAndServeTLSConfig` function.

Since the net/http needs `TLSConfig` set to enable `http/2`, `ListenAndServeTLS` `server.ListenAndServeTLS`, `server.ListenAndServeTLSConfig` and `server.ListenTLS` doesn't have anyway to signal this to `http.Server`.

**Comment by tylerb** [comment]
Great find! I've not investigated http2 at all, so this is excellent. Thanks for this.

Do you have a proposed solution? I am absolutely buried right now and don't have a spare moment to work on this.

**Comment by F21** [comment]
I think we need to see if we can delegate to Go's `ListenAndServeTLS`: https://golang.org/src/net/http/server.go#L2245

This is because it makes a call to `setupHTTP2()`: https://golang.org/src/net/http/server.go#2253

Unfortunately, `setupHTTP2()` is  not exported, so there's no way to call it directly from graceful.

**Comment by tylerb** [comment]
How would you like to take the lead on this? I am swamped and not in a
position to really work on this right now.

**Comment by F21** [comment]
Sure! I will work on a PR today or over the next few days :smile:

**Comment by tylerb** [comment]
Wonderful! Thank you!
