### ISSUE TITLE
Building the next major version of graceful

### ISSUE THREAD

**Issue by F21** [tylerb/graceful#78]
@tylerb mentioned that it is probably a good time to build the next version of graceful with all the lessons learnt while maintaining the library and using it in production. This might be a complete rewrite, or we could refactor it to the next version. We are now interested in what the community would like to see in the next version as well as any feedback you may have.

For starters, these are what we care about the most:
1. Simple, clean, concise public API.
2. Works with any server, like it does now.
3. Supports HTTP 2
4. Robust, correct, clean tests.
5. NOT supporting zero-downtime restarts, there are other packages for that.

**Comment by awalterschulze** [comment]
Might you consider allowing the addition of context which is now included in go1.7
I can catch the os signals myself and call the cancel function.

```
ctx, cancel := context.WithCancel(context.Background())
go func() { 
  // catch os signal
  cancel()
}()
w := sync.WaitGroup{}
w.Add(2)
go func() {
  graceful.RunWithContext(ctx, ":3001",10*time.Second,mux)
  w.Done()
}()
go func() {
  // another background thread
  w.Done()
}
w.Wait()
```

**Comment by F21** [comment]
@awalterschulze I think that's a great idea! Would you be interested in working on a PR?

**Comment by pkieltyka** [comment]
btw, I wrote https://github.com/pressly/valve which is tried to design as an extension to context that provides a shutdown signal and a waitgroup to non-preemptable code blocks finish without just an arbitrary time period. Perhaps something like this could be included directly in a graceful shutdown package.

In addition to the list above, it would be nice to see a graceful package like this one, but designed for any kind of server, not just http servers.

**Comment by F21** [comment]
We may not have to build the next version of Graceful as net/http will probably come with graceful shutdown in Go 1.8: https://github.com/golang/go/issues/4674#issuecomment-257161323

**Comment by tylerb** [comment]
Fantastic!
