### ISSUE TITLE
Using ListenLimit and TCPKeepAlive panics

### ISSUE THREAD

**Issue by djui** [tylerb/graceful#79]
```go
// main.go

package main

import (
	"log"
	"net/http"
	"time"

	"gopkg.in/tylerb/graceful.v1"
)

func main() {
	srv := &graceful.Server{
		ListenLimit:  10,
		TCPKeepAlive: 1 * time.Minute,
		Server: &http.Server{
			Handler: http.NewServeMux(),
			Addr:    ":8080",
		},
	}
	log.Println(srv.ListenAndServe())
}
```

```go
$ go run main.go
panic: interface conversion: net.Listener is *netutil.limitListener, not *net.TCPListener

goroutine 1 [running]:
panic(0x3184e0, 0xc82000e500)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/djui/mb-go/vendor/gopkg.in/tylerb/graceful%2ev1.(*Server).Serve(0xc820080780, 0x1245640, 0xc8200b6760, 0x0, 0x0)
	/Users/abc/dev/go/src/github.com/djui/mb-go/vendor/gopkg.in/tylerb/graceful.v1/graceful.go:242 +0x81f
github.com/djui/mb-go/vendor/gopkg.in/tylerb/graceful%2ev1.(*Server).ListenAndServe(0xc820080780, 0x0, 0x0)
	/Users/abc/dev/go/src/github.com/djui/mb-go/vendor/gopkg.in/tylerb/graceful.v1/graceful.go:151 +0xdf
main.main()
	/Users/abc/dev/go/src/github.com/djui/mb-go/foo.go:20 +0x1a7
exit status 2
```

**Comment by djui** [comment]
Problem is the type conversion at https://github.com/tylerb/graceful/blob/master/graceful.go#L242

Should `tcpKeepAliveListener` embed the `net.Listener` interface instead?

See https://github.com/coreos/etcd/pull/4174/files for an approach.

**Comment by F21** [comment]
@djui That sounds like a better way to do it! Do you mind opening a PR with the fix and a test case including the reproduction you've posted? :smiley:

**Comment by djui** [comment]
@F21 Unfortunately I won't have time the following weeks given how long I think this will take me to implement correctly (and especially test). I'm also not sure about the license to just take ETCDs implementation...

**Comment by F21** [comment]
I think the license should be fine (etcd uses the Apache 2 License), but I am pretty swamped at the moment. Hopefully, someone else can open a PR soon! :smiley:

**Comment by djui** [comment]
@F21 I gave it a quick shot, let me know what you think. Also regarding the license. I am not familiar with the license system to know if the license information needs to be kept, should have a file scope or global scope. So now we use the etcd authors' license (Apache v2) and "sort of" the Go authors' license (Apache v2), as the etcd authors have just overridden the original license.

**Comment by djui** [comment]
While working on this I also discovered a few other quirks that I addressed, see #80, #82.

**Comment by F21** [comment]
@djui Thank you so much for working on those! I will have a look at those tomorrow unless @tylerb beats me to them. Regarding the license, I just noticed graceful uses MIT, but the code from etcd uses Apache 2. Apache 2 is pretty liberal, but let's see what @tylerb thinks.

**Comment by tylerb** [comment]
My understanding is it is just fine as long as the apache header is at the top of the file, which it is, so I think we're good.
