### ISSUE TITLE
TLS doesn't support connection TCPKeepAlive Option

### ISSUE THREAD

**Issue by yanfali** [tylerb/graceful#85]
This issue on etcd explains the issue.

https://github.com/coreos/etcd/pull/2185

**Comment by yanfali** [comment]
To reproduce do something like this:
```
		srv := &graceful.Server{
			Timeout: 10 * time.Second,
			TCPKeepAlive: 3 * time.Minute,
			Server:  &http.Server{Addr: fmt.Sprintf(":%d", port), Handler: n},
			Logger:  graceful.DefaultLogger(),
		}

		err = srv.ListenAndServeTLSConfig(tlsConfig)
```

**Comment by yanfali** [comment]
I can try and work up a PR if you're interested, but it seems relatively straightforward to fix.

**Comment by F21** [comment]
@yanfali Thanks for opening the issue! :smile: If you could open a PR, that would be really awesome too!

**Comment by yanfali** [comment]
@F21 hope this works for the project.

**Comment by F21** [comment]
Closed via #86

**Comment by yanfali** [comment]
@F21 Any timeline when this is going to be released to gopkg.in? I'm using vendoring so I can switch back github, but if you're going to push a release I can wait.  Thanks

**Comment by F21** [comment]
@yanfali Thanks for reminding me! I just pushed `v1.2.12`

**Comment by yanfali** [comment]
Awesome! Thank you.
