### ISSUE TITLE
How to disable http2

### ISSUE THREAD

**Issue by hexadecy** [tylerb/graceful#89]
Since this commit 6dd9b0da0b0b909795cd8186efbe82447244f5a1 http2 is enabled by default with Go 1.7.1.
How can I disabled it, cause MS Edge have SCRIPT7002: XMLHttpRequest: Network Error 0x2eff.

**Comment by mb0** [comment]
Use ListenAndServeTLSConfig  and provide a simple tls.Config with Certificates set from tls.LoadX509KeyPair.

**Comment by F21** [comment]
@hexadecy Were you able to resolve this?

**Comment by hexadecy** [comment]
Yes, I was able to put a flag to disable/enable http2. 
I hope it's just an IE/Edge problem with a self-signed certificate.

**Comment by F21** [comment]
Cool! Let's close this then 😄
